a = input('digite algo')
print('o tipo primitivo desse valor eh: ', type(a))
print('so tem espacos?', a.isspace())
print('eh um numerico?', a.isnumeric())
print('eh alfabetico?', a.isalpha())
print('eh alfanumerico?', a.isalnum())
print('esta em maisculas?', a.isupper())
print('esta em minusculas?', a.islower())
print('esta capitalizado?', a.istitle())
